version: '3'
services:

  fictoon:
      container_name: BakEnd/Fictoon
      image: "pictoon:test"
      ports:
       - "5000:5000"
      networks:
       - backend
  flask:
      container_name: BackEnd/flask
      image: "flask:test"
      ports:
       - "5000:5000"
      networks:
      - backend
  nginx:
      container_name: nginx
      image: "nginx:test"
      ports:
       - "80:80"
      networks:
       - backend

networks:
  backend:
    driver: bridge
